### ISSUE TITLE
Error when running samtools example

### ISSUE THREAD

**Issue by prismofeverything** [googlegenomics/pipelines-api-examples#16]
I am trying to run the samtools example. It ran successfully last Thursday, but today and yesterday it is giving me this error:

```
 "done": true,
 "error": {
  "code": 10,
  "message": "13: VM ggp-1907201874809182950 shut down unexpectedly."
 }
```

Any ideas?

**Comment by deflaux** [comment]
Thank you for this error report.  Can you please try it one or two more times and let us know how it goes?

**Comment by prismofeverything** [comment]
I have tried it maybe 5 times, all with the same result. Here is the operation id if that helps:

```
operations/ENvy44G4Khjmtde3gcDvuxog8ZHMu9UcKg9wcm9kdWN0aW9uUXVldWU
```

Let me know if you need any other information. Thanks for looking into it!

**Comment by deflaux** [comment]
Do you have the genomics api enabled for your project?

**Comment by prismofeverything** [comment]
Yes I do. Like I said, I was able to run the example last Thursday under
the same conditions.

My project id is level-elevator-714 if that helps.

**Comment by tovanadler** [comment]
Could you try changing the service account string to "default" and letting us know how that goes please? (Please include the operation id in your response).

**Comment by prismofeverything** [comment]
Same deal. Here is the operation id:

```operations/EPn7oYa4KhjZ0bTJvuKir40BIPGRzLvVHCoPcHJvZHVjdGlvblF1ZXVl```

**Comment by deflaux** [comment]
@prismofeverything can you please go to https://console.cloud.google.com/start/api?id=genomics and then give the pipeline another try?

**Comment by prismofeverything** [comment]
Hey it worked! What changed then? Did I not have the genomics api enabled before somehow? Was it not required before, then the requirement was added? 

Either way, thanks again!

**Comment by pgrosu** [comment]
Hi Ryan,

Google is fairly transparent via the [API Discovery Service](https://developers.google.com/discovery/), which gives your ability to call services directly given your `ProjectId` and other things, and can be helpful during a troubleshooting session.  You will will notice that this API was recently updated yesterday using the following `curl` command, so it's always good to look to be sure how an API changes - especially new ones - in order to be most up-to-date, which is something I usually try to figure out during a troubleshooting step:

```Bash
$ curl --silent https://www.googleapis.com/discovery/v1/apis/genomics/v1alpha2/rest | grep revision
 "revision": "20160315",
$
```

Thus, you can always determine the required APIs via the following command - this one being specific to the Pipeline API:

```Bash
$ curl --silent https://www.googleapis.com/discovery/v1/apis/genomics/v1alpha2/rest | grep googleapis | cut -f2 -d'"' | grep www | sort | uniq
https://www.googleapis.com/auth/cloud-platform
https://www.googleapis.com/auth/genomics
$
```
Keep in mind that there might be others required beyond the above - namely `https://www.googleapis.com/auth/compute` and `https://www.googleapis.com/auth/devstorage.full_control` - as noted for this entry under `RunPipelineArgs` - which a service would usually prompt you for permission - though some of these are initiated remotely:

```
 "ServiceAccount": {
   "id": "ServiceAccount",
   "type": "object",
   "description": "A Google Cloud Service Account.",
   "properties": {
    "email": {
     "type": "string",
     "description": "Required. Email address of the service account. 'default' is a valid option and uses the compute service account associated with the project."
    },
    "scopes": {
     "type": "array",
     "description": "Required. List of scopes to be made available for this service account. Should include * https://www.googleapis.com/auth/genomics * https://www.googleapis.com/auth/compute * https://www.googleapis.com/auth/devstorage.full_control",
     "items": {
      "type": "string"
     }
    }
   }
  }
```
Hope it helps,
Paul

**Comment by prismofeverything** [comment]
Thank you Paul! That is extremely helpful. Overall very impressed with Google's response on this one. Closing now, and thanks for the great API.
